### ISSUE TITLE
PHP Language and Logo

### ISSUE THREAD

**Issue by MMettille** [johnturner4004/readme-generator#1]
I would love it if you could add PHP to the technology languages!

If you are looking for the devicon, it can be found here with this code: 
```
<!-- in your header -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.13.0/devicon.min.css">

<!-- in your body -->
<i class="devicon-php-plain colored"></i>
```

Thank you!

**Comment by johnturner4004** [comment]
Got it added for you! If it doesn't show up right away try clearing your
cached files and that should fix it. On a mac with chrome its cmd + shift +
delete and the only one that needs checked is "cached images and files."
Plus side to client side only apps is you can host them for free on gh
pages. The down side is that the browser can cache it. Doesn't always
happen but often enough that I'm letting people know as I add stuff for
them.
