### ISSUE TITLE
Add a link to your generator to the "About" section on the GitHub repo landing page

### ISSUE THREAD

**Issue by monicawheeler** [johnturner4004/readme-generator#2]
## Description of request

It is helpful to land on a GitHub page and immediately be able to navigate out to the live site.

![Screen Shot 2021-08-20 at 4 06 32 PM](https://user-images.githubusercontent.com/24237393/130293381-124dd91b-cb0c-40f4-9807-5e560f66b067.png)

**Comment by johnturner4004** [comment]
Hey thanks for the suggestion. I just put one there.
